name: Build wheels

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build wheels on ${{ matrix.os }} / Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel pytest

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Test wheel
        run: |
          pip install dist/*.whl
          pytest tests/
