name: Build wheels
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build wheels on ${{ matrix.os }} / Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Run all builds even if some fail
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel pytest
      - name: Build wheel
        run: |
          python -m build --wheel
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: gh_dist/*
  commit_and_push:
    name: Commit and push dist directory
    runs-on: [ubuntu-latest]
    needs: [build]
    if: success()
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: null # Pull full history
      - name: Download wheels artifacts
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: ./artifacts
      - name: Collect wheels into dist directory
        run: |
          mkdir gh_dist
          for dir in ./artifacts/wheels.* ; do
            cp "$dir"/* gh_dist/
          done
      - name: Commit and push changes
        uses: peter-evans/commit-and-push@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: 'Update dist directory with new artifacts'
          path: ./gh_dist
